# Generated by Django 5.2.2 on 2025-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="created",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
