# Generated by Django 5.2.2 on 2025-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_history_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
