# Generated by Django 5.2.2 on 2025-06-06 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_history_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
